=== felixxkamdjo/xml-transcript/dtd/transcript.dtd
<!-- Root element -->
<!ELEMENT academic_transcript (board_info, grading_scale, student_info, examination_info, subjects, results, footer)>
<!ATTLIST academic_transcript
    version CDATA #REQUIRED
    lang CDATA #REQUIRED
    xmlns:xsi CDATA #IMPLIED
>

<!-- Bilingual text nodes -->
<!ELEMENT fr (#PCDATA)>
<!ELEMENT en (#PCDATA)>

<!-- Institution information -->
<!ELEMENT board_info (board_name, country, exam_title, serial_no)>

<!ELEMENT board_name (fr, en)>
<!ELEMENT country (fr, en)>
<!ELEMENT exam_title (fr, en)>

<!ELEMENT serial_no (#PCDATA)>
<!ATTLIST serial_no
    prefix CDATA #REQUIRED
    number CDATA #REQUIRED
>

<!-- Grading scale definition -->
<!ELEMENT grading_scale (grade_entry+)>

<!ELEMENT grade_entry (letter_grade, class_interval, grade_point, mention)>

<!ELEMENT letter_grade (#PCDATA)>
<!ELEMENT class_interval (#PCDATA)>
<!ELEMENT grade_point (#PCDATA)>
<!ELEMENT mention (fr, en)>

<!-- Student information -->
<!ELEMENT student_info (
    gbtsl_no,
    student_name,
    father_name,
    mother_name,
    institution,
    centre,
    roll_no,
    registration_no,
    type,
    date_of_birth,
    group
)>

<!ELEMENT gbtsl_no (#PCDATA)>
<!ELEMENT student_name (#PCDATA)>
<!ELEMENT father_name (#PCDATA)>
<!ELEMENT mother_name (#PCDATA)>

<!ELEMENT institution (fr, en)>
<!ATTLIST institution
    code CDATA #REQUIRED
>

<!ELEMENT centre (fr, en)>
<!ATTLIST centre
    code CDATA #REQUIRED
>

<!ELEMENT roll_no (#PCDATA)>

<!ELEMENT registration_no (#PCDATA)>
<!ATTLIST registration_no
    academic_year CDATA #REQUIRED
>

<!ELEMENT type (fr, en)>

<!ELEMENT date_of_birth (#PCDATA)>
<!ATTLIST date_of_birth
    format CDATA #REQUIRED
>

<!ELEMENT group (fr, en)>

<!-- Examination information -->
<!ELEMENT examination_info (exam_year, publication_date)>

<!ELEMENT exam_year (#PCDATA)>
<!ELEMENT publication_date (fr, en)>

<!-- Subjects container -->
<!ELEMENT subjects (mandatory_subjects, optional_subjects, continuous_assessment)>

<!ELEMENT mandatory_subjects (subject+)>
<!ELEMENT optional_subjects (subject+)>
<!ELEMENT continuous_assessment (subject+)>

<!ELEMENT subject (subject_name, letter_grade, grade_point)>
<!ATTLIST subject
    sl_no CDATA #REQUIRED
    type (mandatory | optional | continuous) #REQUIRED
>

<!ELEMENT subject_name (fr, en)>

<!-- Results section -->
<!ELEMENT results (
    gpa_without_optional,
    gpa_above_optional,
    final_gpa,
    mention
)>

<!ELEMENT gpa_without_optional (#PCDATA)>
<!ELEMENT gpa_above_optional (#PCDATA)>
<!ELEMENT final_gpa (#PCDATA)>

<!-- Footer section -->
<!ELEMENT footer (compared_by?, controller)>

<!ELEMENT compared_by (#PCDATA)>
<!ELEMENT controller (fr, en)>

=== felixxkamdjo/xml-transcript/xml/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/transcript.xsl"?>

<!DOCTYPE academic_transcript SYSTEM "../dtd/transcript.dtd">


<academic_transcript
    version="1.0"
    lang="fr-en"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- Institution information -->
    <board_info>
        <board_name>
            <fr>Ecole Nationale Superieure Polytechnique de Douala</fr>
            <en>National Higher Polytechnic School of Douala</en>
        </board_name>
        <country>
            <fr>Cameroun</fr>
            <en>Cameroon</en>
        </country>
        <exam_title>
            <fr>Releve de Notes — Semestre 06 — Genie Logiciel</fr>
            <en>Academic Transcript — Semester 06 — Software Engineering</en>
        </exam_title>
        <serial_no prefix="/" number="24G01763">/24G01763</serial_no>
    </board_info>

    <!-- Grading scale -->
    <grading_scale>
        <grade_entry>
            <letter_grade>A</letter_grade>
            <class_interval>16-20</class_interval>
            <grade_point>4.00</grade_point>
            <mention>
                <fr>Tres Bien</fr>
                <en>Excellent</en>
            </mention>
        </grade_entry>
        <grade_entry>
            <letter_grade>B</letter_grade>
            <class_interval>14-15</class_interval>
            <grade_point>3.00</grade_point>
            <mention>
                <fr>Bien</fr>
                <en>Good</en>
            </mention>
        </grade_entry>
        <grade_entry>
            <letter_grade>C</letter_grade>
            <class_interval>12-13</class_interval>
            <grade_point>2.00</grade_point>
            <mention>
                <fr>Assez Bien</fr>
                <en>Satisfactory</en>
            </mention>
        </grade_entry>
        <grade_entry>
            <letter_grade>D</letter_grade>
            <class_interval>10-11</class_interval>
            <grade_point>1.00</grade_point>
            <mention>
                <fr>Passable</fr>
                <en>Pass</en>
            </mention>
        </grade_entry>
        <grade_entry>
            <letter_grade>E</letter_grade>
            <class_interval>08-09</class_interval>
            <grade_point>0.50</grade_point>
            <mention>
                <fr>Insuffisant</fr>
                <en>Insufficient</en>
            </mention>
        </grade_entry>
        <grade_entry>
            <letter_grade>F</letter_grade>
            <class_interval>00-07</class_interval>
            <grade_point>0.00</grade_point>
            <mention>
                <fr>Echec</fr>
                <en>Fail</en>
            </mention>
        </grade_entry>
    </grading_scale>

    <!-- Student information -->
    <student_info>
        <gbtsl_no>24G01763</gbtsl_no>
        <student_name>Kamdjo Felix Junior</student_name>
        <father_name>Kamdjo Jean Felix</father_name>
        <mother_name>Moche Rita</mother_name>
        <institution code="/">
            <fr>Ecole Nationale Superieure Polytechnique de Douala</fr>
            <en>National Advanced School of Engineering of Douala</en>
        </institution>
        <centre code="DLA">
            <fr>Douala</fr>
            <en>Douala</en>
        </centre>
        <roll_no>24G01763</roll_no>
        <registration_no academic_year="2024-2025">24G01763</registration_no>
        <type>
            <fr>Regulier</fr>
            <en>Regular</en>
        </type>
        <date_of_birth format="DD/MM/YYYY">15/10/2003</date_of_birth>
        <group>
            <fr>Genie Logiciel</fr>
            <en>Software Engineering</en>
        </group>
    </student_info>

    <!-- Examination information -->
    <examination_info>
        <exam_year>2025</exam_year>
        <publication_date>
            <fr>02 juillet 2025</fr>
            <en>July 02, 2025</en>
        </publication_date>
    </examination_info>

    <!-- Subjects -->
    <subjects>

        <!-- Mandatory subjects -->
        <mandatory_subjects>
            <subject sl_no="1" type="mandatory">
                <subject_name>
                    <fr>Architecture Logicielle et Patrons de Conception</fr>
                    <en>Software Architecture and Design Patterns</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="2" type="mandatory">
                <subject_name>
                    <fr>Developpement Web Avance (Frontend / Backend)</fr>
                    <en>Advanced Web Development (Frontend / Backend)</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="3" type="mandatory">
                <subject_name>
                    <fr>Bases de Donnees Avancees et NoSQL</fr>
                    <en>Advanced Databases and NoSQL</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="4" type="mandatory">
                <subject_name>
                    <fr>Systemes d'Exploitation et Administration Reseau</fr>
                    <en>Operating Systems and Network Administration</en>
                </subject_name>
                <letter_grade>B</letter_grade>
                <grade_point>3.00</grade_point>
            </subject>
            <subject sl_no="5" type="mandatory">
                <subject_name>
                    <fr>Methodes Agiles et DevOps</fr>
                    <en>Agile Methods and DevOps</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="6" type="mandatory">
                <subject_name>
                    <fr>Securite des Systemes d'Information</fr>
                    <en>Information Systems Security</en>
                </subject_name>
                <letter_grade>B</letter_grade>
                <grade_point>3.00</grade_point>
            </subject>
            <subject sl_no="7" type="mandatory">
                <subject_name>
                    <fr>Intelligence Artificielle et Apprentissage Automatique</fr>
                    <en>Artificial Intelligence and Machine Learning</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="8" type="mandatory">
                <subject_name>
                    <fr>Compilation et Langages Formels</fr>
                    <en>Compilation and Formal Languages</en>
                </subject_name>
                <letter_grade>B</letter_grade>
                <grade_point>3.00</grade_point>
            </subject>
            <subject sl_no="9" type="mandatory">
                <subject_name>
                    <fr>Probabilites et Statistiques Appliquees</fr>
                    <en>Applied Probability and Statistics</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
        </mandatory_subjects>

        <!-- Optional subjects -->
        <optional_subjects>
            <subject sl_no="10" type="optional">
                <subject_name>
                    <fr>Entrepreneuriat et Innovation Technologique</fr>
                    <en>Entrepreneurship and Technological Innovation</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
        </optional_subjects>

        <!-- Continuous assessment -->
        <continuous_assessment>
            <subject sl_no="11" type="continuous">
                <subject_name>
                    <fr>Projet de Developpement Logiciel (Travaux Pratiques)</fr>
                    <en>Software Development Project (Practical Work)</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
            <subject sl_no="12" type="continuous">
                <subject_name>
                    <fr>Communication Professionnelle et Technique</fr>
                    <en>Professional and Technical Communication</en>
                </subject_name>
                <letter_grade>A</letter_grade>
                <grade_point>4.00</grade_point>
            </subject>
        </continuous_assessment>

    </subjects>

    <!-- Results -->
    <results>
        <gpa_without_optional>3.78</gpa_without_optional>
        <gpa_above_optional>4.00</gpa_above_optional>
        <final_gpa>4.00</final_gpa>
        <mention>
            <fr>Tres Bien</fr>
            <en>Excellent</en>
        </mention>
    </results>

    <!-- Footer -->
    <footer>
        <compared_by></compared_by>
        <controller>
            <fr>Le Directeur des Etudes</fr>
            <en>Director of Academic Affairs</en>
        </controller>
    </footer>

</academic_transcript>
